# Site settings
title: Geil,Danke!
email: kontakt@geildanke.com
description: > # this means to ignore newlines until "baseurl:"
  Apps, Websites, Games, Magazines. Multiplatform design, development, consulting, production and publishing.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://geildanke.com" # the base hostname & protocol for your site
twitter_username: geildanke
github_username:  geildanke

# Build settings
markdown: kramdown

collections:
  projecttiles:
  projects:
    output: true
  products:

gems:
- jekyll-compass