# Site settings
title: Geil,Danke!
email: kontakt@geildanke.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://geildanke.com" # the base hostname & protocol for your site
twitter_username: geildanke
github_username:  geildanke
main_host: https://geildanke.com

# Build settings
markdown: kramdown

collections:
  corecompetences:
    output: true
  ctas:
  footerlists:
  lists:
  projecttiles:
  projects:
    output: true
  products:
  services:

sass:
  sass_dir: _assets/stylesheets
  style: compressed

gems: [jekyll-assets, autoprefixer-rails]